# Generated by Django 4.2.4 on 2024-05-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_myproduct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
