# Generated by Django 4.2.4 on 2024-05-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_myproduct', '0002_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.IntegerField(default=0),
        ),
    ]
