# Generated by Django 4.2.4 on 2024-05-10 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_banking.user')),
            ],
        ),
    ]
