# Generated by Django 4.2.4 on 2024-05-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banking', '0002_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
